sudo: required

language: java
jdk: openjdk11

addons:
  apt:
    packages:
      - docker-ce

script:
  - mvn clean test -B
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

after_success:
  - bash <(curl -s https://codecov.io/bash)

  # TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - export APPLEPRICESBOT=proshik/applepricesbot
  - export COMMIT=${TRAVIS_COMMIT::7}
  
  - docker build -t $APPLEPRICESBOT:$COMMIT .
  - docker tag $APPLEPRICESBOT:$COMMIT $APPLEPRICESBOT:$TAG
  - docker push $APPLEPRICESBOT:$TAG
